/* Version information autogenerated CMAKE*/
#ifndef  g4NeutronXS_NAME
#define g4NeutronXS_NAME "g4NeutronXS"
#define g4NeutronXS_VERSION       "HEAD-HASH-NOTFOUND"
#define g4NeutronXS_MAJOR_VERSION 0
#define g4NeutronXS_MINOR_VERSION 0
#define g4NeutronXS_PATCH_VERSION 0
#define BEFORE_g4NeutronXS(v,r,p) ((g4NeutronXS_MAJOR_VERSION==(v)&&g4NeutronXS_MINOR_VERSION==(r)&&g4NeutronXS_PATCH_VERSION<(p))||(g4NeutronXS_MAJOR_VERSION==(v)&&g4NeutronXS_MINOR_VERSION<(r))||(g4NeutronXS_MAJOR_VERSION<(v)))
#define EQUALS_g4NeutronXS(v,r,p) (g4NeutronXS_MAJOR_VERSION==(v)&&g4NeutronXS_MINOR_VERSION==(r)&&g4NeutronXS_PATCH_VERSION==(p))
#define g4NeutronXS_COMPILE_HOST  "dump.pas.rochester.edu"
#define g4NeutronXS_COMPILE_UNAME "Linux dump.pas.rochester.edu 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux"
#define g4NeutronXS_COMPILE_DIR "/home/jelias/T2K/work/software/MoNA_imp/g4NeutronXS_0.0/cmake"

#endif 

